AllCops:
  TargetRubyVersion: 2.3

# Do not ever break my development console, RuboCop
Lint/Debugger:
  Exclude:
    - 'bin/console'

# It is 2016. Please, use UTF-8 everywhere
Style/AsciiComments:
  Enabled: false

# Do not ever use double quotes without interpolation
Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/LineLength:
  Exclude:
    - 'lib/vk/schema/model'
    - 'lib/vk/schema/types'

inherit_from: .rubocop_todo.yml
