#!/usr/bin/env ruby
# coding: utf-8

require 'pathname'
require 'time'
require 'fileutils'
require 'open-uri'
require 'vk'
require 'vk/dsl'
require 'active_support/core_ext/string/inflections'

## Set client up

begin
  require 'dotenv'
  Dotenv.load('.env') if File.exist?('.env')
rescue LoadError
end
Vk.app_id = ENV['VK_APP_ID']
Vk.app_secret = ENV['VK_APP_SECRET']

client = Vk::Client.authenticated!
Vk.client.access_token = client.access_token

backup_at = Time.now


# Fetch information about user, her albums and audios

user = client.get_me
path = Pathname.new('.').join('backups', user.id, backup_at.xmlschema.slice(0..18).gsub(':', '-'))
FileUtils.mkdir_p(path.to_s)
puts 'Audios'
user.audios.each_with_index do |audio, index|
  file = path
  file = file.join(audio.album.title.parameterize) if audio.album
  file = file.join([index + 1, audio.artist, audio.title].join(' — ') << '.mp3')
  puts audio.artist, audio.title, file

  unless file.exist?
    # File.write(file.to_s, open(audio.url).read)
    `curl -o "#{file}" "#{audio.url}"`
  end
end
puts 'Albums'
user.audio_albums.each do |album|
  puts album.title
end
